name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
      
    steps:
    - uses: actions/checkout@v2
    # build with GNU to avoid MSVCRT140.dll dependency
    - name: Add windows gnu toolchain
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
      if: matrix.os == 'windows-latest'
    - name: Set windows gnu toolchain as default
      run: rustup default stable-x86_64-pc-windows-gnu
      if: matrix.os == 'windows-latest'
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Github connect test
      run: cargo run --release -- --tls www.github.com :443
    - name: Run workflow commands
      id: cmds
      run: cargo run --release -- --release-workflow-commands x
    - name: Zip release files (unix)
      run: cd target/release; zip "ackreport-${{ steps.cmds.outputs.os_name }}-${{ steps.cmds.outputs.version }}.zip" ackreport
      if: steps.cmds.outputs.os_name != 'windows'
    - name: Zip release files (windows)
      run: cd target/release; Compress-Archive -DestinationPath "ackreport-${{ steps.cmds.outputs.os_name }}-${{ steps.cmds.outputs.version }}.zip" -Path ackreport.exe
      if: steps.cmds.outputs.os_name == 'windows'
    - uses: softprops/action-gh-release@v1
      with:
        name: ackreport ${{ steps.cmds.outputs.version }}
        files: "target/release/ackreport-${{ steps.cmds.outputs.os_name }}-${{ steps.cmds.outputs.version }}.zip"
        body_path: release.txt
