name: Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Github connect test
      run: cargo run --release -- --tls www.github.com :443
    - name: Run workflow commands
      id: cmds
      run: cargo run --release -- --release-workflow-commands x
    - uses: actions/upload-artifact@v3
      with:
        name: ackreport-${{ steps.cmds.outputs.os_name }}-${{ steps.cmds.outputs.version }}
        path: target/release/ackreport${{ steps.cmds.outputs.exe_suffix }}

