name: Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Run workflow commands
      id: cmds
      run: cargo run --release -- --release-workflow-commands x
    - name: Run bad ssl examples
      run: cargo run -- --tls badssl.com :80 badssl.com :99 no-common-name.badssl.com wrong.host.badssl.com self-signed.badssl.com revoked.badssl.com 1000-sans.badssl.com ecc384.badssl.com rsa8192.badssl.com mitm-software.badssl.com :443
    - name: local ip check
      run: cargo run -- badssl.com :99
    - uses: actions/upload-artifact@v3
      with:
        name: ackreport-${{ steps.cmds.outputs.os_name }}-${{ steps.cmds.outputs.version }}
        path: target/release/ackreport${{ steps.cmds.outputs.exe_suffix }}

